import os
from pathlib import Path


# Install Dependencies/Setup compile_commands.json through PlatformIO
Import("env")

env.Execute("$PYTHONEXE -m pip install -r requirements.txt")

# include toolchain paths
env.Replace(COMPILATIONDB_INCLUDE_TOOLCHAIN=True)

# override compilation DB path
env.Replace(COMPILATIONDB_PATH="compile_commands.json")


import sys
from collections import OrderedDict

# Append python-tools/q8bot to the path so that we can import it
path = Path() / ".." / ".." / "python-tools"
sys.path.append(str(path.resolve()))

from q8bot.kinematics_solver import k_solver
from q8bot.gait_manager import GaitManager, GAITS, GAIT_DIRECTIONS

# Q8bot leg configuration
CENTER_DIST = 19.5  # Distance between two actuators
L1 = 25             # Upper leg length
L2 = 40             # Lower leg length

leg = k_solver(CENTER_DIST, L1, L2, L1, L2)
gait_names = list(GAITS.keys())
gait_manager = GaitManager(leg, GAITS)

precomputed_gaits = OrderedDict()

for dir in GAIT_DIRECTIONS:
    for gait in gait_names:
        gait_manager.load_gait(gait)
        gait_manager.start_movement(dir)
        precomputed_gaits[f"{gait}_{dir}"] = gait_manager.current_trajectory

# Get the number of motors per movement
motors_per_movement = len(list(precomputed_gaits.values())[0][0])
for name, trajectory in precomputed_gaits.items():
    for movements in trajectory:
        assert len(movements) == motors_per_movement, f"ERROR: This trajectory ({name}) has a non-uniform number of motor movements"


header = f"""// *DO NOT EDIT THIS FILE*
// This file was autogenerated by python-tools/q8bot/gait_lut.py

#ifndef _GAIT_LUT_GENERATED_H
#define _GAIT_LUT_GENERATED_H

#include <stdint.h>

#ifndef __INCLUDING_GENERATED_LUTS
    #error "Please don't include _gait_lut_generated.h! Include gait_lut.h instead!"
#endif

typedef int32_t movement_t[{motors_per_movement}];\n
"""


# Enum for the gaits
header += "enum gait_t {\n"

for k in precomputed_gaits.keys():
    header += f"\t{k.replace(".", "_")},\n"

header += "};\n\n"


# The LUT which stores the gaits
header += "const static movement_t GaitLUT[] = {\n"

gait_offsets = OrderedDict()
curr_offset = 0
for name, trajectory in precomputed_gaits.items():
    gait_offsets[name.replace(".", "_")] = curr_offset
    for movements in trajectory:
        header += f"\t{{ {", ".join([str(int(x)) for x in movements])} }},\n"
        curr_offset += 1

header += "};\n\n"


# Generate offsets so we know how many movements make up each gait. Indexed by enum values.
header += "const static unsigned short GaitLUTOffsets[] = {\n"

for offset in gait_offsets.values():
    header += f"\t{offset},\n"

header += "};\n\n"

header += "#endif // _GAIT_LUT_GENERATED_H"

with open(str(Path("include") / "_gait_lut_generated.h"), "w") as f:
    f.write(header)